### ISSUE TITLE
1.20.1版本无法兼容

### ISSUE THREAD

**Issue by yuxi7712** [BingZi-233/BilibiliVideo#7]
首先非常感谢你制作并延续了这款插件，我一直在寻找它的更新。
我在1.20.1版本中使用过程中输入/bilibili-video login
它无法弹出地图的二维码让我登录哔站

以下是我在尝试输入登录指令后出现的报错
```text
17:48:49] [Server thread/INFO] [net.minecraft.server.network.ServerGamePacketListenerImpl]: yuxi_ issued server command: /bilibili-video login
[17:48:49] [Craft Scheduler Thread - 4/ERROR] [net.minecraftforge.fml.loading.RuntimeDistCleaner]: Attempted to load class net/minecraft/client/RecipeBookCategories for invalid dist DEDICATED_SERVER
[17:48:49] [Craft Scheduler Thread - 4/WARN] [online.bingiz.bilibili.video.taboolib.platform.BukkitPlugin]: [BilibiliVideo] Plugin BilibiliVideo v1.0.5-1 generated an exception while executing task 188
java.lang.IllegalStateException: MapInitializeEvent cannot be triggered asynchronously from another thread.
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:581) ~[forge-1.20.1-47.2.6-universal.jar%23219!/:?]
	at net.minecraft.world.item.MapItem.m_151120_(MapItem.java:90) ~[server-1.20.1-20230612.114412-srg.jar%23214!/:?]
	at org.bukkit.craftbukkit.v1_20_R1.CraftServer.createMap(CraftServer.java:1572) ~[forge-1.20.1-47.2.6-universal.jar%23219!/:997de31d-ddc9a2dad-d2eba2c8-47.2.6]
	at org.bukkit.craftbukkit.v1_20_R1.CraftServer.createMap(CraftServer.java:271) ~[forge-1.20.1-47.2.6-universal.jar%23219!/:997de31d-ddc9a2dad-d2eba2c8-47.2.6]
	at org.bukkit.Bukkit.createMap(Bukkit.java:785) ~[forge-1.20.1-47.2.6-universal.jar%23219!/:?]
	at online.bingiz.bilibili.video.taboolib.module.nms.NMSMap$mapView$2.invoke(NMSMap.kt:215) ~[?:?]
	at online.bingiz.bilibili.video.taboolib.module.nms.NMSMap$mapView$2.invoke(NMSMap.kt:214) ~[?:?]
	at kotlin1510.UnsafeLazyImpl.getValue(Lazy.kt:81) ~[?:?]
	at online.bingiz.bilibili.video.taboolib.module.nms.NMSMap.getMapView(NMSMap.kt:214) ~[?:?]
	at online.bingiz.bilibili.video.taboolib.module.nms.NMSMap$mapItem$2$1.invoke(NMSMap.kt:230) ~[?:?]
	at online.bingiz.bilibili.video.taboolib.module.nms.NMSMap$mapItem$2$1.invoke(NMSMap.kt:230) ~[?:?]
	at online.bingiz.bilibili.video.taboolib.platform.util.ItemModifierKt.modifyMeta(ItemModifier.kt:46) ~[?:?]
	at online.bingiz.bilibili.video.taboolib.module.nms.NMSMap$mapItem$2.invoke(NMSMap.kt:230) ~[?:?]
	at online.bingiz.bilibili.video.taboolib.module.nms.NMSMap$mapItem$2.invoke(NMSMap.kt:220) ~[?:?]
	at kotlin1510.UnsafeLazyImpl.getValue(Lazy.kt:81) ~[?:?]
	at online.bingiz.bilibili.video.taboolib.module.nms.NMSMap.getMapItem(NMSMap.kt:220) ~[?:?]
	at online.bingiz.bilibili.video.taboolib.module.nms.NMSMap$sendTo$1.invoke(NMSMap.kt:248) ~[?:?]
	at online.bingiz.bilibili.video.taboolib.module.nms.NMSMap$sendTo$1.invoke(NMSMap.kt:237) ~[?:?]
	at online.bingiz.bilibili.video.taboolib.platform.BukkitExecutor$submit$4.run(BukkitExecutor.kt:71) ~[?:?]
	at org.bukkit.craftbukkit.v1_20_R1.scheduler.CraftTask.run(CraftTask.java:78) ~[forge-1.20.1-47.2.6-universal.jar%23219!/:?]
	at org.bukkit.craftbukkit.v1_20_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:55) [forge-1.20.1-47.2.6-universal.jar%23219!/:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) [?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) [?:?]
	at java.lang.Thread.run(Thread.java:833) [?:?]
```

**Comment by yuxishinidie** [comment]
您好大佬，很高兴您可以帮忙处理这个问题，如果方便 我想添加您的联系方式

**Comment by BingZi-233** [comment]
该错误应该已被修复，请查看关联构建构件。若已解决问题请关闭。

**Comment by yuxi7712** [comment]
非常感谢您解决了此问题，但是遗憾的是新的问题出现了
登录成功后，我使用/bilibili-video receive BV1Qs411d7pd
提示：获取稿件信息失败，账户登录数据已失效
我再次扫码后，再次输入，会出现同样的提示

**Comment by yuxi7712** [comment]
很抱歉，我还是无法打开二维码
以下是出现的错误信息
[12:56:08] [Server thread/INFO] [net.minecraft.server.network.ServerGamePacketListenerImpl]: yuxi_ issued server command: /bilibili-video login
[12:56:09] [Server thread/ERROR] [net.minecraftforge.fml.loading.RuntimeDistCleaner]: Attempted to load class net/minecraft/client/RecipeBookCategories for invalid dist DEDICATED_SERVER

我不知道应该怎么做
--------
就在刚刚我做出了错误的操作
在没有删除BilibiliVideo-1.0.5-1 版本的情况下在插件文件夹中又添加了您刚才更新的BilibiliVideo-1.0.6版本插件
服务器运行成功后，我尝试登录并且成功的打开了二维码
扫码后输入/bilibili-video receive BV1Qs411d7pd
提示：获取稿件信息失败，账户登陆数据已失效。
之后我发现了我的操作错误
并且删掉了1.0.5-5版本，删除了原有配置文件
并重新加载1.0.6版本插件
可是我还是无法打开二维码进行登录
麻烦您了大佬
